// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Head from "next/head";

((require("bulma")));

function Page(Props) {
  var children = Props.children;
  return React.createElement(React.Fragment, undefined, React.createElement(Head.default, {
                  children: null
                }, React.createElement("meta", {
                      content: "width=device-width, initial-scale=1, shrink=to-fit=no, viewport=fit=cover",
                      name: "viewport"
                    }), React.createElement("title", undefined, "ReasonReact with Next.js")), children);
}

var make = Page;

export {
  make ,
  
}
/*  Not a pure module */
