// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Hero$ReasonNextjs from "../src/components/layout/Hero.bs.js";
import * as Posts$ReasonNextjs from "./posts.bs.js";

function Index(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(Hero$ReasonNextjs.make, {
                  title: "Blog",
                  subtitle: "Reason + Next.js"
                }), React.createElement(Posts$ReasonNextjs.make, { }));
}

var make = Index;

var $$default = Index;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
